#!/usr/bin/env node
// Turns the research CSV export into SQL for the research schema
// (supabase/migrations/20260926000002_research_workspace.sql).
//
//   node scripts/research/load.mjs <folder-with-csvs> > research.sql
//   node scripts/research/load.mjs --append <folder-with-csvs> > research.sql
//
// Then run research.sql in the Supabase SQL editor, or with psql. By default
// it replaces everything in the research tables, so re-running it with a
// newer export is safe. With --append it only adds rows whose id and name
// aren't there yet, and never changes or deletes a row already loaded; a
// row's market (the CSV column, which has no table column) goes at the start
// of its notes. Expects activities.csv, organizations.csv, places.csv,
// events.csv.
//
// The CSVs and the generated SQL contain contact details and internal notes:
// keep them out of this repository.

import { readFileSync } from "node:fs";
import { join } from "node:path";

const append = process.argv.includes("--append");
const folder = process.argv.slice(2).find((a) => a !== "--append");
if (!folder) {
  console.error("Usage: node scripts/research/load.mjs [--append] <folder-with-csvs>");
  process.exit(1);
}

/** RFC 4180 CSV: quoted fields may contain commas, quotes ("") and newlines. */
export function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = "";
  let quoted = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c === '"' && text[i + 1] === '"') {
        field += '"';
        i++;
      } else if (c === '"') {
        quoted = false;
      } else {
        field += c;
      }
    } else if (c === '"') {
      quoted = true;
    } else if (c === ",") {
      row.push(field);
      field = "";
    } else if (c === "\n" || c === "\r") {
      if (c === "\r" && text[i + 1] === "\n") i++;
      row.push(field);
      rows.push(row);
      row = [];
      field = "";
    } else {
      field += c;
    }
  }
  if (field !== "" || row.length) {
    row.push(field);
    rows.push(row);
  }
  const [header, ...body] = rows.filter((r) => r.some((v) => v !== ""));
  return body.map((r) => Object.fromEntries(header.map((h, i) => [h.trim(), (r[i] ?? "").trim()])));
}

const read = (name) => parseCsv(readFileSync(join(folder, name), "utf8").replace(/^﻿/, ""));

const text = (v) => (v === "" || v == null ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const list = (v) =>
  `array[${(v ?? "")
    .split(";")
    .map((s) => s.trim())
    .filter(Boolean)
    .map(text)
    .join(", ")}]::text[]`;
const bool = (v) => (/^(y|yes|true)$/i.test(v ?? "") ? "true" : "false");
const date = (v) => (/^\d{4}-\d{2}-\d{2}$/.test(v ?? "") ? `'${v}'::date` : "null::date");
const orgRefs = (v) => `array[${[...new Set((v ?? "").match(/ORG-\d+/g) ?? [])].map(text).join(", ")}]::text[]`;

// Append mode: the row is new only when nothing already loaded shares its
// id, or (for named rows) its name, ignoring case and spaces.
const sameAs = {
  activities: (t) => `${t}.activity_id = v.activity_id`,
  organizations: (t) => `${t}.org_id = v.org_id or lower(btrim(${t}.name)) = lower(btrim(v.name))`,
  places: (t) => `${t}.place_id = v.place_id or lower(btrim(${t}.name)) = lower(btrim(v.name))`,
  events: (t) =>
    `${t}.event_id = v.event_id or (lower(btrim(${t}.name)) = lower(btrim(v.name)) and ${t}.start_date is not distinct from v.start_date)`,
};

function insert(table, columns, rows, values) {
  if (!rows.length) return "";
  const tuples = rows.map((r) => `  (${values(r).join(", ")})`).join(",\n");
  if (!append) return `insert into research.${table} (${columns.join(", ")}) values\n${tuples};\n`;
  return (
    `insert into research.${table} (${columns.join(", ")})\n` +
    `select * from (values\n${tuples}\n) as v (${columns.join(", ")})\n` +
    `where not exists (select 1 from research.${table} x where ${sameAs[table]("x")});\n`
  );
}

/** In append mode, keep the CSV's market (no table column) at the start of the notes. */
const withMarket = (r) => (append && r.market ? [`Market: ${r.market}.`, r.notes].filter(Boolean).join(" ") : r.notes);

const activities = read("activities.csv");
const organizations = read("organizations.csv");
const places = read("places.csv");
const events = read("events.csv");

const sql = [
  "-- Generated by scripts/research/load.mjs. Contains research data: do not commit.",
  "begin;",
  append ? "-- Append only: existing rows are kept as they are." : "truncate research.events, research.places, research.organizations, research.activities;",
  insert("activities", ["activity_id", "label", "category"], activities, (r) => [text(r.activity_id), text(r.label), text(r.category)]),
  insert(
    "organizations",
    ["org_id", "name", "org_type", "status", "activities", "area", "website", "source_listing_url", "community_fit", "women_specific", "notes", "address", "phone", "verified", "source"],
    organizations,
    (r) => [
      text(r.org_id), text(r.name), text(r.org_type), text(r.status), list(r.activities), text(r.area), text(r.website),
      text(r.source_listing_url), text(r.community_fit), text(r.women_specific), text(withMarket(r)), text(r.address), text(r.phone),
      bool(r.verified), text(r.source),
    ],
  ),
  insert(
    "places",
    ["place_id", "name", "place_type", "area", "activities", "verified", "source_url", "notes", "source"],
    places,
    (r) => [text(r.place_id), text(r.name), text(r.place_type), text(r.area), list(r.activities), bool(r.verified), text(r.source_url), text(withMarket(r)), text(r.source)],
  ),
  insert(
    "events",
    [
      "event_id", "name", "event_type", "price", "capacity", "min_age", "status", "women_specific", "start_date", "end_date", "start_time",
      "end_time", "recurrence", "venue", "organizer", "organizer_ids", "activities", "url", "booking_url", "notes", "verified", "source",
    ],
    events,
    (r) => [
      text(r.event_id), text(r.name), text(r.event_type), text(r.price), text(r.capacity), text(r.min_age), text(r.status), text(r.women_specific),
      date(r.start_date), date(r.end_date), text(r.start_time), text(r.end_time), text(r.recurrence), text(r.venue), text(r.organizer),
      orgRefs(r.organizer), list(r.activities), text(r.url), text(r.booking_url), text(withMarket(r)), bool(r.verified), text(r.source),
    ],
  ),
  "commit;",
  `-- ${activities.length} activities, ${organizations.length} organizations, ${places.length} places, ${events.length} events`,
].join("\n");

process.stdout.write(sql + "\n");
